### ISSUE TITLE
API call for stream fails because of presence of 'x-auth-token' query param

### ISSUE THREAD

**Issue by agaffney** [StackStorm/st2chatops#10]
I'm unsure if this is an issue with this Docker image (really, the versions of various things in it) or something else, but I'm running into issues. I've tried this with both ST2 1.3.x and 1.4dev.

When hubot tries to query /v1/stream, it uses a request like the following (which is proxied through nginx):

```
172.17.0.36 - - [12/Feb/2016:16:45:20 -0800] "GET /api/v1/stream?x-auth-token=9e1fdd874bf04c0ba0789ced62f51d97 HTTP/1.1" 500 46 "-" "-"
```

The 500 error is returned because of this error in `st2api.log`:

```
2016-02-12 16:38:30,274 139669775957680 ERROR log [-] API call failed: get_all() got an unexpected keyword argument 'x-auth-token'
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/pecan/core.py", line 631, in __call__
    self.invoke_controller(controller, args, kwargs, state)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/pecan/core.py", line 531, in invoke_controller
    result = controller(*args, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/models/api/base.py", line 245, in callfunction
    raise e
TypeError: get_all() got an unexpected keyword argument 'x-auth-token' (_exception_data={},_exception_class='TypeError',_exception_message="get_all() got an unexpected keyword argument 'x-auth-token'")
```

As far as I can tell, this request form is allowed by ST2.

**Comment by agaffney** [comment]
This is what I see from Hubot:

```
[Sat Feb 13 2016 00:45:18 GMT+0000 (UTC)] INFO Connecting...
[Sat Feb 13 2016 00:45:20 GMT+0000 (UTC)] INFO Logged in as autoops of Turn, but not yet connected
[Sat Feb 13 2016 00:45:20 GMT+0000 (UTC)] INFO Slack client now connected
[Sat Feb 13 2016 00:45:20 GMT+0000 (UTC)] INFO Requesting a token...
[Sat Feb 13 2016 00:45:20 GMT+0000 (UTC)] INFO Token received. Expiring 2016-02-14T00:45:20.413307Z
[Sat Feb 13 2016 00:45:20 GMT+0000 (UTC)] INFO Loading commands....
[Sat Feb 13 2016 00:45:20 GMT+0000 (UTC)] ERROR Stream error: Event { type: 'error', status: 500 }
[Sat Feb 13 2016 00:45:20 GMT+0000 (UTC)] INFO 0 commands are loaded
```

**Comment by agaffney** [comment]
This was happening because auth was disabled in ST2 but Hubot was trying to use auth.
