### ISSUE TITLE
body-parser deprecated undefined extended: provide extended option prevent st2chatops start

### ISSUE THREAD

**Issue by dove-young** [StackStorm/st2chatops#152]
I installed StackStorm 3.2.0 via ansible playbook
```
ansible-playbook stackstorm.yml --verbose
```

Git HEAD of ansible playbook is 

```
commit 97108985f3351d696d3413f2db3cf3d43eb43a89
Merge: 86a1cec 35abf1d
Author: JP Bourget <jp.bourget@gmail.com>
Date:   Tue Apr 14 13:40:42 2020 -0400

    Merge pull request #258 from StackStorm/custom_nginx

    Custom nginx
```

When I try to start `st2chatops`, it failed to start with error messages like

```
systemctl status st2chatops
● st2chatops.service - StackStorm service st2chatops
   Loaded: loaded (/usr/lib/systemd/system/st2chatops.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Sun 2020-06-21 21:36:00 PDT; 6min ago
  Process: 15385 ExecStart=/opt/stackstorm/chatops/bin/hubot $DAEMON_ARGS (code=exited, status=0/SUCCESS)
 Main PID: 15385 (code=exited, status=0/SUCCESS)

Jun 21 21:35:59 agentavtone-masterone.fyre.ibm.com systemd[1]: Started StackStorm service st2chatops.
Jun 21 21:36:00 agentavtone-masterone.fyre.ibm.com hubot[15385]: Mon, 22 Jun 2020 04:36:00 GMT body-parser deprecated undefined extended: provide extended option at node_modules/hubot/src/...t.js:445:21
Jun 21 21:36:00 agentavtone-masterone.fyre.ibm.com hubot[15385]: [Sun Jun 21 2020 21:36:00 GMT-0700 (Pacific Daylight Time)] DEBUG Loading adapter shell
Jun 21 21:36:00 agentavtone-masterone.fyre.ibm.com hubot[15385]: No history available
Jun 21 21:36:00 agentavtone-masterone.fyre.ibm.com hubot[15385]: [137B blob data]
Jun 21 21:36:00 agentavtone-masterone.fyre.ibm.com hubot[15385]: [Sun Jun 21 2020 21:36:00 GMT-0700 (Pacific Daylight Time)] DEBUG Loading scripts from /opt/stackstorm/chatops/src/scripts
Hint: Some lines were ellipsized, use -l to show in full.
```

I can run `./bin/hubot --adapter slack` from command line and I can get hubot connect to my Slack workspace. 

```
HUBOT_SLACK_TOKEN=xoxb-my-token HUBOT_ADAPTER=slack HUBOT_LOG_LEVEL=debug HUBOT_SLACK_RTM_CLIENT_OPTS='{ "logLevel": "de
bug" }' HUBOT_SLACK_RTM_CLIENT_OPTS='{ "retryConfig": { "retries": 20 } }' HUBOT_SLACK_RTM_START_OPTS='{ "mpim_aware": true }'  ./bin/hubot --adapter slack

body-parser deprecated undefined extended: provide extended option node_modules/hubot/src/robot.js:445:21
[Sun Jun 21 2020 21:38:06 GMT-0700 (Pacific Daylight Time)] DEBUG Loading adapter slack
[Sun Jun 21 2020 21:38:07 GMT-0700 (Pacific Daylight Time)] INFO hubot-slack adapter v4.5.5
warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.
warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.
[Sun Jun 21 2020 21:38:07 GMT-0700 (Pacific Daylight Time)] DEBUG RtmClient initialized with options: {"retryConfig":{"retries":20},"maxRequestConcurrency":1}
[Sun Jun 21 2020 21:38:07 GMT-0700 (Pacific Daylight Time)] DEBUG RtmClient#start() with options: {"mpim_aware":true}
[Sun Jun 21 2020 21:38:08 GMT-0700 (Pacific Daylight Time)] DEBUG SlackBot#authenticated() Found self in RTM start data
[Sun Jun 21 2020 21:38:08 GMT-0700 (Pacific Daylight Time)] INFO Logged in as @hubot in workspace hubot-test-20
[Sun Jun 21 2020 21:38:09 GMT-0700 (Pacific Daylight Time)] INFO Connected to Slack RTM
```

The log message from command line also claims `body-parser deprecated undefined extended`.  Seem like this error prevented `st2chatops` service start via `systemctl`. 

```
body-parser deprecated undefined extended: provide extended option node_modules/hubot/src/robot.js:445:21
```

**Comment by amanda11** [comment]
I checked my running st2chatops and I can see in my journalctl logs "Jun 22 09:32:33 centos-8-stackstorm hubot[9156]: Mon, 22 Jun 2020 09:32:33 GMT body-parser deprecated undefined extended: provide extended option at node_modules/hubot/src/robot.js:445:21"

But my st2chatops is running fine.  So the problems isn't with that message.

In your /opt/stackstorm/chatops/st2chatops.env - can you check you just have a single HUBOT_ADAPTER uncommented (I have seen issues when more than one is uncommented).

I presume you require it to be set to slack. Is the HUBOT_ADAPTER set to slack, and HUBOT_SLACK_TOKEN set in the st2chatops.env? 

There are some troubleshooting instructions at https://docs.stackstorm.com/troubleshooting/basic_chatops_troubleshooting.html which may help.

**Comment by arm4b** [comment]
What's the platform/environment you're running in?
