### ISSUE TITLE
chatops.post_message crashes st2chatops using Rocket.Chat

### ISSUE THREAD

**Issue by MrDiba** [StackStorm/st2chatops#169]
## SUMMARY

Manually triggering chatops.post_message results in a crash of st2chatops using Rocket.Chat.

### STACKSTORM VERSION

```
$ st2 --version
st2 3.4.1, on Python 3.6.9

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
...

installed using the following command:
bash <(curl -sSL https://stackstorm.com/packages/install.sh) --user=st2admin --password=Ch@ngeMe --version=3.4.1

```

## Steps to reproduce the problem

1. Install StackStorm on a clean VM. (I'm using StackStorm version 3.4.1 because of #167)
2. Configure st2chatops by editing the `/opt/stackstorm/chatops/st2chatops.env
3. Test if the bot replies from Rocket.Chat: `hubot help` results in a list with commands
4. `tail -f /var/log/syslog` and try `!st2 list actions` 
The bot returns: `Give me just a moment to find the actions for you... (details available at <url_omitted>)`
The log shows some action and task handling until:
```
Aug  9 12:10:42 stackstorm hubot[12591]: [Mon Aug 09 2021 12:10:42 GMT+0000 (Coordinated Universal Time)] ERROR TypeError: Cannot read property 'roomID' of undefined
Aug  9 12:10:42 stackstorm hubot[12591]:     at strings.map (/opt/stackstorm/chatops/node_modules/hubot-rocketchat/index.js:155:25)
Aug  9 12:10:42 stackstorm hubot[12591]:     at Array.map (<anonymous>:null:null)
Aug  9 12:10:42 stackstorm hubot[12591]:     at RocketChatBotAdapter.send (/opt/stackstorm/chatops/node_modules/hubot-rocketchat/index.js:154:20)
Aug  9 12:10:42 stackstorm hubot[12591]:     at Robot.messageRoom (/opt/stackstorm/chatops/node_modules/hubot/src/robot.js:608:23)
Aug  9 12:10:42 stackstorm hubot[12591]:     at sendChunk (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/src/lib/adapters/rocketchat.js:73:25)
Aug  9 12:10:42 stackstorm hubot[12591]:     at RocketChatAdapter.postData (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/src/lib/adapters/rocketchat.js:78:5)
Aug  9 12:10:42 stackstorm hubot[12591]:     at EventSource.<anonymous> (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/src/lib/stackstorm_api.js:453:20)
Aug  9 12:10:42 stackstorm hubot[12591]:     at EventSource.emit (events.js:198:13)
Aug  9 12:10:42 stackstorm hubot[12591]:     at _emit (/opt/stackstorm/chatops/node_modules/eventsource/lib/eventsource.js:172:17)
Aug  9 12:10:42 stackstorm hubot[12591]:     at parseEventStreamLine (/opt/stackstorm/chatops/node_modules/eventsource/lib/eventsource.js:186:9)
Aug  9 12:10:42 stackstorm hubot[12591]:     at IncomingMessage.<anonymous> (/opt/stackstorm/chatops/node_modules/eventsource/lib/eventsource.js:150:11)
Aug  9 12:10:42 stackstorm hubot[12591]:     at IncomingMessage.emit (events.js:198:13)
Aug  9 12:10:42 stackstorm hubot[12591]:     at addChunk (_stream_readable.js:288:12)
Aug  9 12:10:42 stackstorm hubot[12591]:     at readableAddChunk (_stream_readable.js:269:11)
Aug  9 12:10:42 stackstorm hubot[12591]:     at IncomingMessage.Readable.push (_stream_readable.js:224:10)
Aug  9 12:10:42 stackstorm hubot[12591]:     at HTTPParser.parserOnBody (_http_common.js:124:22)
Aug  9 12:10:42 stackstorm hubot[12591]:     at TLSSocket.socketOnData (_http_client.js:451:20)
Aug  9 12:10:42 stackstorm hubot[12591]:     at TLSSocket.emit (events.js:198:13)
Aug  9 12:10:42 stackstorm hubot[12591]:     at addChunk (_stream_readable.js:288:12)
Aug  9 12:10:42 stackstorm hubot[12591]:     at readableAddChunk (_stream_readable.js:269:11)
Aug  9 12:10:42 stackstorm hubot[12591]:     at TLSSocket.Readable.push (_stream_readable.js:224:10)
Aug  9 12:10:42 stackstorm hubot[12591]:     at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Aug  9 12:10:42 stackstorm hubot[12591]: [Mon Aug 09 2021 12:10:42 GMT+0000 (Coordinated Universal Time)] ERROR TypeError: Cannot read property 'roomID' of undefined
Aug  9 12:10:42 stackstorm hubot[12591]:     at strings.map (/opt/stackstorm/chatops/node_modules/hubot-rocketchat/index.js:155:25)
Aug  9 12:10:42 stackstorm hubot[12591]:     at Array.map (<anonymous>:null:null)
Aug  9 12:10:42 stackstorm hubot[12591]:     at RocketChatBotAdapter.send (/opt/stackstorm/chatops/node_modules/hubot-rocketchat/index.js:154:20)
Aug  9 12:10:42 stackstorm hubot[12591]:     at Robot.messageRoom (/opt/stackstorm/chatops/node_modules/hubot/src/robot.js:608:23)
Aug  9 12:10:42 stackstorm hubot[12591]:     at sendChunk (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/src/lib/adapters/rocketchat.js:73:25)
Aug  9 12:10:42 stackstorm hubot[12591]:     at RocketChatAdapter.postData (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/src/lib/adapters/rocketchat.js:78:5)
Aug  9 12:10:42 stackstorm hubot[12591]:     at EventSource.<anonymous> (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/src/lib/stackstorm_api.js:453:20)
Aug  9 12:10:42 stackstorm hubot[12591]:     at EventSource.emit (events.js:198:13)
Aug  9 12:10:42 stackstorm hubot[12591]:     at _emit (/opt/stackstorm/chatops/node_modules/eventsource/lib/eventsource.js:172:17)
Aug  9 12:10:42 stackstorm hubot[12591]:     at parseEventStreamLine (/opt/stackstorm/chatops/node_modules/eventsource/lib/eventsource.js:186:9)
Aug  9 12:10:42 stackstorm hubot[12591]:     at IncomingMessage.<anonymous> (/opt/stackstorm/chatops/node_modules/eventsource/lib/eventsource.js:150:11)
Aug  9 12:10:42 stackstorm hubot[12591]:     at IncomingMessage.emit (events.js:198:13)
Aug  9 12:10:42 stackstorm hubot[12591]:     at addChunk (_stream_readable.js:288:12)
Aug  9 12:10:42 stackstorm hubot[12591]:     at readableAddChunk (_stream_readable.js:269:11)
Aug  9 12:10:42 stackstorm hubot[12591]:     at IncomingMessage.Readable.push (_stream_readable.js:224:10)
Aug  9 12:10:42 stackstorm hubot[12591]:     at HTTPParser.parserOnBody (_http_common.js:124:22)
Aug  9 12:10:42 stackstorm hubot[12591]:     at TLSSocket.socketOnData (_http_client.js:451:20)
Aug  9 12:10:42 stackstorm hubot[12591]:     at TLSSocket.emit (events.js:198:13)
Aug  9 12:10:42 stackstorm hubot[12591]:     at addChunk (_stream_readable.js:288:12)
Aug  9 12:10:42 stackstorm hubot[12591]:     at readableAddChunk (_stream_readable.js:269:11)
Aug  9 12:10:42 stackstorm hubot[12591]:     at TLSSocket.Readable.push (_stream_readable.js:224:10)
Aug  9 12:10:42 stackstorm hubot[12591]:     at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Aug  9 12:10:42 stackstorm hubot[12591]: [Mon Aug 09 2021 12:10:42 GMT+0000 (Coordinated Universal Time)] INFO Hubot will shut down ...
Aug  9 12:10:42 stackstorm hubot[12591]: [Mon Aug 09 2021 12:10:42 GMT+0000 (Coordinated Universal Time)] WARNING Stream error: Event { type: 'error' }
```

### Manually triggering chatops.post_message:
1. Open chatops.post_message action (https://<vm_ip>/#/actions/chatops.post_message).
2. Enter Rocket.Chat room name at `channel` and a test message at `message`.
3.  `tail -f /var/log/syslog` and click run.
4. The StackStorm history shows a successful execution.
5. The syslog shows a less successful execution:
```
Aug  9 11:05:30 stackstorm st2scheduler[6444]: 2021-08-09 11:05:30,708 INFO [-] [61110bfa823a28a7e056383d] Retrieved item "61110bfae7bba26eb7af2b29" from scheduling queue.
Aug  9 11:05:30 stackstorm st2scheduler[6444]: 2021-08-09 11:05:30,711 INFO [-] [61110bfa823a28a7e056383d] Scheduling Liveaction "61110bfa823a28a7e056383c". (queue_item_id='61110bfae7bba26eb7af2b29')
Aug  9 11:05:30 stackstorm st2scheduler[6444]: 2021-08-09 11:05:30,713 INFO [-] [61110bfa823a28a7e056383d] Liveaction "61110bfa823a28a7e056383c" with status "requested" is updated to status "scheduled." (queue_item_id='61110bfae7bba26eb7af2b29')
Aug  9 11:05:30 stackstorm st2scheduler[6444]: 2021-08-09 11:05:30,750 INFO [-] The status of action execution is changed from requested to scheduled. <LiveAction.id=61110bfa823a28a7e056383c, ActionExecution.id=61110bfa823a28a7e056383d>
Aug  9 11:05:30 stackstorm st2actionrunner[11119]: 2021-08-09 11:05:30,782 INFO [-] Dispatched {~}action_execution: 61110bfa823a28a7e056383d / {~}live_action: 61110bfa823a28a7e056383c with "running" status.
Aug  9 11:05:30 stackstorm st2actionrunner[11119]: 2021-08-09 11:05:30,786 INFO [-] Dispatching Action to a runner (liveaction_db={'action': 'chatops.post_message', 'action_is_workflow': False, 'callback': {}, 'context': {'trace_context': {}, 'user': 'st2admin', 'pack': 'chatops'}, 'delay': None, 'end_timestamp': None, 'id': '61110bfa823a28a7e056383c', 'notify': None, 'parameters': {'channel': 'IT', 'message': 'testmessage'}, 'result': {}, 'runner_info': {'hostname': 'stackstorm', 'pid': 11119}, 'start_timestamp': '2021-08-09 11:05:30.660666+00:00', 'status': 'running', 'task_execution': None, 'workflow_execution': None},runner_type_db={'description': 'A runner for emitting an announcement event on the stream.', 'enabled': True, 'id': '610d37b8a1e45fa40ff5251d', 'name': 'announcement', 'output_key': None, 'output_schema': {}, 'query_module': None, 'runner_module': 'announcement_runner', 'runner_package': 'announcement_runner', 'runner_parameters': {'experimental': {'default': False, 'description': 'Flag to indicate acknowledgment of using experimental runner', 'required': True, 'type': 'boolean'}, 'route': {'default': 'general', 'description': 'The routing_key used to route the message to consumers. Might be a list of words, delimited by dots.', 'maxLength': 255, 'minLength': 1, 'type': 'string'}}, 'uid': 'runner_type:announcement'})
Aug  9 11:05:30 stackstorm hubot[17042]: [Mon Aug 09 2021 11:05:30 GMT+0000 (Coordinated Universal Time)] DEBUG Chatops message received: {"payload": {"extra": null, "context": null, "whisper": false, "user": null, "message": "testmessage", "channel": "IT"}, "trace_context": {}}
Aug  9 11:05:30 stackstorm hubot[17042]: [Mon Aug 09 2021 11:05:30 GMT+0000 (Coordinated Universal Time)] ERROR TypeError: Cannot read property 'roomID' of undefined
Aug  9 11:05:30 stackstorm hubot[17042]:     at strings.map (/opt/stackstorm/chatops/node_modules/hubot-rocketchat/index.js:155:25)
Aug  9 11:05:30 stackstorm hubot[17042]:     at Array.map (<anonymous>:null:null)
Aug  9 11:05:30 stackstorm hubot[17042]:     at RocketChatBotAdapter.send (/opt/stackstorm/chatops/node_modules/hubot-rocketchat/index.js:154:20)
Aug  9 11:05:30 stackstorm hubot[17042]:     at Robot.messageRoom (/opt/stackstorm/chatops/node_modules/hubot/src/robot.js:608:23)
Aug  9 11:05:30 stackstorm hubot[17042]:     at sendChunk (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/src/lib/adapters/rocketchat.js:73:25)
Aug  9 11:05:30 stackstorm hubot[17042]:     at RocketChatAdapter.postData (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/src/lib/adapters/rocketchat.js:78:5)
Aug  9 11:05:30 stackstorm hubot[17042]:     at EventSource.<anonymous> (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/src/lib/stackstorm_api.js:453:20)
Aug  9 11:05:30 stackstorm hubot[17042]:     at EventSource.emit (events.js:198:13)
Aug  9 11:05:30 stackstorm hubot[17042]:     at _emit (/opt/stackstorm/chatops/node_modules/eventsource/lib/eventsource.js:172:17)
Aug  9 11:05:30 stackstorm hubot[17042]:     at parseEventStreamLine (/opt/stackstorm/chatops/node_modules/eventsource/lib/eventsource.js:186:9)
Aug  9 11:05:30 stackstorm hubot[17042]:     at IncomingMessage.<anonymous> (/opt/stackstorm/chatops/node_modules/eventsource/lib/eventsource.js:150:11)
Aug  9 11:05:30 stackstorm hubot[17042]:     at IncomingMessage.emit (events.js:198:13)
Aug  9 11:05:30 stackstorm hubot[17042]:     at addChunk (_stream_readable.js:288:12)
Aug  9 11:05:30 stackstorm hubot[17042]:     at readableAddChunk (_stream_readable.js:269:11)
Aug  9 11:05:30 stackstorm hubot[17042]:     at IncomingMessage.Readable.push (_stream_readable.js:224:10)
Aug  9 11:05:30 stackstorm hubot[17042]:     at HTTPParser.parserOnBody (_http_common.js:124:22)
Aug  9 11:05:30 stackstorm hubot[17042]:     at TLSSocket.socketOnData (_http_client.js:451:20)
Aug  9 11:05:30 stackstorm hubot[17042]:     at TLSSocket.emit (events.js:198:13)
Aug  9 11:05:30 stackstorm hubot[17042]:     at addChunk (_stream_readable.js:288:12)
Aug  9 11:05:30 stackstorm hubot[17042]:     at readableAddChunk (_stream_readable.js:269:11)
Aug  9 11:05:30 stackstorm hubot[17042]:     at TLSSocket.Readable.push (_stream_readable.js:224:10)
Aug  9 11:05:30 stackstorm hubot[17042]:     at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Aug  9 11:05:30 stackstorm hubot[17042]: [Mon Aug 09 2021 11:05:30 GMT+0000 (Coordinated Universal Time)] ERROR TypeError: Cannot read property 'roomID' of undefined
Aug  9 11:05:30 stackstorm hubot[17042]:     at strings.map (/opt/stackstorm/chatops/node_modules/hubot-rocketchat/index.js:155:25)
Aug  9 11:05:30 stackstorm hubot[17042]:     at Array.map (<anonymous>:null:null)
Aug  9 11:05:30 stackstorm hubot[17042]:     at RocketChatBotAdapter.send (/opt/stackstorm/chatops/node_modules/hubot-rocketchat/index.js:154:20)
Aug  9 11:05:30 stackstorm hubot[17042]:     at Robot.messageRoom (/opt/stackstorm/chatops/node_modules/hubot/src/robot.js:608:23)
Aug  9 11:05:30 stackstorm hubot[17042]:     at sendChunk (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/src/lib/adapters/rocketchat.js:73:25)
Aug  9 11:05:30 stackstorm hubot[17042]:     at RocketChatAdapter.postData (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/src/lib/adapters/rocketchat.js:78:5)
Aug  9 11:05:30 stackstorm hubot[17042]:     at EventSource.<anonymous> (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/src/lib/stackstorm_api.js:453:20)
Aug  9 11:05:30 stackstorm hubot[17042]:     at EventSource.emit (events.js:198:13)
Aug  9 11:05:30 stackstorm hubot[17042]:     at _emit (/opt/stackstorm/chatops/node_modules/eventsource/lib/eventsource.js:172:17)
Aug  9 11:05:30 stackstorm hubot[17042]:     at parseEventStreamLine (/opt/stackstorm/chatops/node_modules/eventsource/lib/eventsource.js:186:9)
Aug  9 11:05:30 stackstorm hubot[17042]:     at IncomingMessage.<anonymous> (/opt/stackstorm/chatops/node_modules/eventsource/lib/eventsource.js:150:11)
Aug  9 11:05:30 stackstorm hubot[17042]:     at IncomingMessage.emit (events.js:198:13)
Aug  9 11:05:30 stackstorm hubot[17042]:     at addChunk (_stream_readable.js:288:12)
Aug  9 11:05:30 stackstorm hubot[17042]:     at readableAddChunk (_stream_readable.js:269:11)
Aug  9 11:05:30 stackstorm hubot[17042]:     at IncomingMessage.Readable.push (_stream_readable.js:224:10)
Aug  9 11:05:30 stackstorm hubot[17042]:     at HTTPParser.parserOnBody (_http_common.js:124:22)
Aug  9 11:05:30 stackstorm hubot[17042]:     at TLSSocket.socketOnData (_http_client.js:451:20)
Aug  9 11:05:30 stackstorm hubot[17042]:     at TLSSocket.emit (events.js:198:13)
Aug  9 11:05:30 stackstorm hubot[17042]:     at addChunk (_stream_readable.js:288:12)
Aug  9 11:05:30 stackstorm hubot[17042]:     at readableAddChunk (_stream_readable.js:269:11)
Aug  9 11:05:30 stackstorm hubot[17042]:     at TLSSocket.Readable.push (_stream_readable.js:224:10)
Aug  9 11:05:30 stackstorm hubot[17042]:     at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Aug  9 11:05:30 stackstorm hubot[17042]: [Mon Aug 09 2021 11:05:30 GMT+0000 (Coordinated Universal Time)] INFO Hubot will shut down ...
Aug  9 11:05:30 stackstorm hubot[17042]: [Mon Aug 09 2021 11:05:30 GMT+0000 (Coordinated Universal Time)] WARNING Stream error: Event { type: 'error' }
Aug  9 11:05:30 stackstorm st2rulesengine[6445]: 2021-08-09 11:05:30,873 INFO [-] Found 0 rules defined for trigger core.st2.generic.actiontrigger
Aug  9 11:05:30 stackstorm st2rulesengine[6445]: 2021-08-09 11:05:30,875 INFO [-] No matching rules found for trigger instance 61110bfad482a41b070b836b.
Aug  9 11:05:31 stackstorm hubot[17042]: [Mon Aug 09 2021 11:05:31 GMT+0000 (Coordinated Universal Time)] DEBUG Chatops message received: {"payload": {"extra": null, "context": null, "whisper": false, "user": null, "message": "testmessage", "channel": "IT"}, "trace_context": {}}
Aug  9 11:05:31 stackstorm hubot[17042]: /opt/stackstorm/chatops/node_modules/hubot-rocketchat/index.js:155
Aug  9 11:05:31 stackstorm hubot[17042]:       if (envelope.user.roomID) driver.sendToRoomId(text, envelope.user.roomID)
Aug  9 11:05:31 stackstorm hubot[17042]:                         ^
Aug  9 11:05:31 stackstorm hubot[17042]: TypeError: Cannot read property 'roomID' of undefined
Aug  9 11:05:31 stackstorm hubot[17042]:     at strings.map (/opt/stackstorm/chatops/node_modules/hubot-rocketchat/index.js:155:25)
Aug  9 11:05:31 stackstorm hubot[17042]:     at Array.map (<anonymous>:null:null)
Aug  9 11:05:31 stackstorm hubot[17042]:     at RocketChatBotAdapter.send (/opt/stackstorm/chatops/node_modules/hubot-rocketchat/index.js:154:20)
Aug  9 11:05:31 stackstorm hubot[17042]:     at Robot.messageRoom (/opt/stackstorm/chatops/node_modules/hubot/src/robot.js:608:23)
Aug  9 11:05:31 stackstorm hubot[17042]:     at sendChunk (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/src/lib/adapters/rocketchat.js:73:25)
Aug  9 11:05:31 stackstorm hubot[17042]:     at RocketChatAdapter.postData (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/src/lib/adapters/rocketchat.js:78:5)
Aug  9 11:05:31 stackstorm hubot[17042]:     at EventSource.<anonymous> (/opt/stackstorm/chatops/node_modules/hubot-stackstorm/src/lib/stackstorm_api.js:453:20)
Aug  9 11:05:31 stackstorm hubot[17042]:     at EventSource.emit (events.js:198:13)
Aug  9 11:05:31 stackstorm hubot[17042]:     at _emit (/opt/stackstorm/chatops/node_modules/eventsource/lib/eventsource.js:172:17)
Aug  9 11:05:31 stackstorm hubot[17042]:     at parseEventStreamLine (/opt/stackstorm/chatops/node_modules/eventsource/lib/eventsource.js:186:9)
Aug  9 11:05:31 stackstorm hubot[17042]:     at IncomingMessage.<anonymous> (/opt/stackstorm/chatops/node_modules/eventsource/lib/eventsource.js:150:11)
Aug  9 11:05:31 stackstorm hubot[17042]:     at IncomingMessage.emit (events.js:198:13)
Aug  9 11:05:31 stackstorm hubot[17042]:     at addChunk (_stream_readable.js:288:12)
Aug  9 11:05:31 stackstorm hubot[17042]:     at readableAddChunk (_stream_readable.js:269:11)
Aug  9 11:05:31 stackstorm hubot[17042]:     at IncomingMessage.Readable.push (_stream_readable.js:224:10)
Aug  9 11:05:31 stackstorm hubot[17042]:     at HTTPParser.parserOnBody (_http_common.js:124:22)
Aug  9 11:05:31 stackstorm hubot[17042]:     at TLSSocket.socketOnData (_http_client.js:451:20)
Aug  9 11:05:31 stackstorm hubot[17042]:     at TLSSocket.emit (events.js:198:13)
Aug  9 11:05:31 stackstorm hubot[17042]:     at addChunk (_stream_readable.js:288:12)
Aug  9 11:05:31 stackstorm hubot[17042]:     at readableAddChunk (_stream_readable.js:269:11)
Aug  9 11:05:31 stackstorm hubot[17042]:     at TLSSocket.Readable.push (_stream_readable.js:224:10)
Aug  9 11:05:31 stackstorm hubot[17042]:     at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Aug  9 11:05:31 stackstorm systemd[1]: st2chatops.service: Main process exited, code=exited, status=1/FAILURE
Aug  9 11:05:31 stackstorm systemd[1]: st2chatops.service: Failed with result 'exit-code'.
Aug  9 11:05:37 stackstorm systemd[1]: st2chatops.service: Service hold-off time over, scheduling restart.
Aug  9 11:05:37 stackstorm systemd[1]: st2chatops.service: Scheduled restart job, restart counter is at 10.
Aug  9 11:05:37 stackstorm systemd[1]: Stopped StackStorm service st2chatops.
Aug  9 11:05:37 stackstorm systemd[1]: Started StackStorm service st2chatops.
```

**Comment by MrDiba** [comment]
Okay, I have found a fix (workaround) for the problem.

The problem is not StackStorm related but is upstream with the hubot-rocketchat adapter. Here https://github.com/RocketChat/hubot-rocketchat-boilerplate/issues/4#issuecomment-389711070 is a fix specified.

A pull request (https://github.com/RocketChat/hubot-rocketchat/pull/283 ) has been made but not merged.

**Comment by nzlosh** [comment]
@MrDiba An alternative to StackStorm's hubot is [err-stackstorm](https://err-stackstorm.readthedocs.io/en/latest/) which is based on errbot.  You may find errbot supports rocketchat out-of-the-box.

**Comment by blag** [comment]
👆
